spring.application.name=placement-backend
server.port=8081

# MySQL Configuration
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/orbit_placement?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Diby@Subham007

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Cloudinary Configuration
cloudinary.cloud_name=dnfsoc190
cloudinary.api_key=735623683647561
cloudinary.api_secret=kfreJ-3VCTLiSCGHmj4n-rJ4CQU

# JWT Configuration
jwt.secret=orbitPlacementSuperSecretKey1234567890OrbitPlacementSuperSecretKey1234567890
jwt.expiration=86400000
